### ISSUE TITLE
herokuish procfile start deletes my local project

### ISSUE THREAD

**Issue by iDiogenes** [gliderlabs/herokuish#25]
Hello,
I could be doing something incorrectly, but I am trying to launch herokuish image as part of a cluster using docker-compose.

my docker-compose.yml has the following:

```
web:
  build: .
  env_file: .env
  command: herokuish procfile start
  ports:
   - "5000:5000"
  volumes:
   - .:/app
  links:
   - mongo
mongo:
  image: stepsaway/mongo:2.6.9
  ports:
   - "27017:27017"
```

My docker files look like 

```
FROM gliderlabs/herokuish:latest

WORKDIR /tmp/app
ADD . /tmp/app

RUN herokuish buildpack build

WORKDIR /app
ADD . /app
```

I run *docker-compose build* and then *docker-compose up*. It is my understanding that during the up command the Procfile should be read and ran which should bring up my webapp. However, what I am seeing is the following:
```
Recreating sapi_mongo_1...
Recreating sapi_web_1...
Attaching to sapi_web_1
web_1 | rm: cannot remove '/app': Device or resource busy
web_1 | cat: /app/Procfile: No such file or directory
sapi_web_1 exited with code 6
Gracefully stopping... (press Ctrl+C again to force)
```

Followed by my entire project being deleted on my laptop. Is this a bug or am I not understanding how I should be using herokuish correctly.

Thanks for any help and thanks for creating this image.
