### ISSUE TITLE
Cannot execute any Procfile commands 

### ISSUE THREAD

**Issue by ViViDboarder** [gliderlabs/herokuish#321]
For some reason I can run `herokuish test` just fine, however `herokuish procfile start web` is failing and not printing any kind of message. It just exits with code 8. I also tried playing around interactively and didn't have any luck. `herokuish procfile exec echo test` or any other command will exit with code 8 as well.

`docker-compose.yml`
```
version: '2'
services:
  web:
    image: gliderlabs/herokuish
    volumes:
      - .:/tmp/app
    ports:
      - 3000:3000
    entrypoint: ["/bin/herokuish"]
    # command: ["test"]
    # command: ["procfile", "start", "web"]
```

`Procfile`
```
web: bin/rails server -p $PORT
```
