### ISSUE TITLE
Change node js and php detection order

### ISSUE THREAD

**Issue by spyderz42** [gliderlabs/herokuish#691]
The PHP composer.json file is only used in php projects where the node package.json is used in all sorts of projects. Can you move 09_buildpack-php to 02? Or probably better, move 02_buildpack-nodejs down to 09? I am currently working around this in the gitlab autodevops ci/cd by adding some pre and post scripts to the pipeline

```yaml
build:
  before_script:
    - echo https://github.com/heroku/heroku-buildpack-php > .buildpacks
  after_script:
    - rm .buildpacks

test:
  before_script:
    - rm package.json
```
